server {
    listen 3000;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location ~ ^(.+)/$ {
        return 308 $1$is_args$args;
    }

    location / {
        try_files $uri.html $uri $uri/index.html =404;
    }

    error_page 404 /404.html;

    location = /404.html {
        internal;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
